### ISSUE TITLE
Cloaking-rules BUG, Not support both ipv4 and ipv6

### ISSUE THREAD

**Issue by wang20150419** [DNSCrypt/dnscrypt-proxy#733] opened 2019-02-20 07:06 UTC
version:  2.0.19
cloaking-rules.txt：
#------------------
localhost                127.0.0.1
test.xyz                 111.111.111.111
test.xyz                 2000:7834:1016::1
#------------------

dig test.xyz
   ;; QUESTION SECTION:
;test.xyz.                      IN      A
;; ANSWER SECTION:
test.xyz.               600     IN      A       111.111.111.111

dig test.xyz AAAA
;; QUESTION SECTION:
;test.xyz.                      IN      AAAA

**Comment by jedisct1** [comment] 2019-02-20 09:28
Not a bug, but there can be only one IP address per zone.

But why would you like to use different resolvers for different query types?

**Comment by wang20150419** [comment] 2019-02-20 14:12
overture dns (https://github.com/shawn1m/overture) support it，dnsmasq also support it.
In my office, the wired network is dual-stack, the wireless network only supports ipv4,
Using ipv6 can save VPS's widthwide. Such as: visit Google can go ipv6 line. but in only
 ipv4 network, it is accessed via VPS. (Using  the same dnscrypt-proxy server)

**Comment by wang20150419** [comment] 2019-02-20 14:13
> Not a bug, but there can be only one IP address per zone.
> 
> But why would you like to use different resolvers for different query types?

overture dns (https://github.com/shawn1m/overture) support it，dnsmasq also support it.
In my office, the wired network is dual-stack, the wireless network only supports ipv4,
Using ipv6 can save VPS's widthwide. Such as: visit Google can go ipv6 line. but in only
ipv4 network, it is accessed via VPS. (Using the same dnscrypt-proxy server)

**Comment by jedisct1** [comment] 2019-02-20 14:35
But in that case, why not always access the resolver over IPv6?

It shouldn't make any difference to the type of queries it can respond to.

**Comment by wang20150419** [comment] 2019-02-20 16:34
> But in that case, why not always access the resolver over IPv6?
> 
> It shouldn't make any difference to the type of queries it can respond to.

Because the wireless network is only ipv4 network. it can't access ipv6. Almost all  google's ipv4 addresses are blocked, and some google's ipv6 addresses( not from dns-server ) are accessible. 

in my case, the google's ipv6 address is real IP address(can't get form public dns server) , the google's ipv4 address is my sni_proxy address.

**Comment by jedisct1** [comment] 2019-02-21 11:56
Oh, I see, I was confusing cloaking and forwarding.

**Comment by jedisct1** [comment] 2019-02-21 11:58
Duplicate of #617

**Closed as completed by jedisct1** 2019-02-21 11:58 UTC
Labels: duplicate
