### ISSUE TITLE
whitelists

### ISSUE THREAD

**Issue by CNMan** [DNSCrypt/dnscrypt-proxy#117] opened 2018-02-11 08:16 UTC
for example:
blocking rules:`github.com`
cloaking rules:`api.github.com 192.30.255.116`

currently dnscrypt-proxy block all *.github.com including api.github.com.
i want to block main-domain but whitelist some sub-domian,how to config it?thanks

**Comment by jedisct1** [comment] 2018-02-11 09:56
I don't think this is currently possible.

So, probably the best way to solve this and add some overall flexibility would be to add a whitelist set to the blocking rules, that would have a higher priority than other rules.

**Comment by Biggizen** [comment] 2018-02-17 01:44
Whitelisting would be awsome!

**Comment by jedisct1** [comment] 2018-02-17 08:59
+1

**Comment by jedisct1** [comment] 2018-02-27 13:38
Duplicate of #198

**Closed as completed by jedisct1** 2018-02-27 13:38 UTC
Labels: duplicate, feature request
