### ISSUE TITLE
DNSCrypt Proxy SystemD unit file has no dependencies

### ISSUE THREAD

**Issue by FabrizioMarana** [DNSCrypt/dnscrypt-proxy#1208] opened 2020-02-26 10:17 UTC
## *Who* is the bug affecting?
systemd users

## *What* is affected by this bug?
dns-crypt proxy startup

## *When* does this occur?
Boot

## *Where* does it happen?
[Here](https://forum.manjaro.org/t/funky-systemd-network-things-going-on-my-raspberry-pi-4/125614) intermittently during boot.

## *How* do we replicate the issue?
Booting the system intermittent error:
Sometimes dnscrypt-proxy service needs to be restarted manually.

## Expected behavior (i.e. solution)
**Solution:**
Include at the top of the DNS-crypt proxy service file the following:
```
[Unit]
Description=DNS Crypt Proxy
Requires=NetworkManager.target
#After=systemd-logind.service
```
**Why?**
Now DNS Crypt Proxy does not have any dependencies and on rare occasions will start before the network is ready.  By forcing it to wait until NetworkManager has started, this eliminates the problem.  

## Other Comments
1. The user that has this issue still has to test.  I'll update after that.
2. Not all distro's use NetworkManager, so do some extra digging for Debian and CentOS which might still be using Network service instead of NetworkManager, which will change the dependency.

**Comment by jedisct1** [comment] 2020-02-26 14:25
Looks like a duplicate of https://github.com/kardianos/service/issues/77

**Closed as completed by jedisct1** 2020-02-26 14:25 UTC
Labels: systemd, linux
