### ISSUE TITLE
dnscrypt proxy 2.0.15-1 breaks for me

### ISSUE THREAD

**Issue by mneyrane** [DNSCrypt/dnscrypt-proxy#500] opened 2018-06-14 22:16 UTC
Greetings. I am not sure if this is the right place to go but I'll try to be as informative as I can.

I recently upgraded `dnscrypt-proxy` from version 2.0.14-2 to 2.0.15-1, and any program I have utilizing DNS does not work in this new version. Packet analysis using `tcpdump` shows no DNS queries being made from my laptop, however I can SSH into my servers and ping over the WAN and LAN, so this is unlikely a network issue.

Strangely enough, `systemd` is not providing any warnings or failure from the service or socket. Here is my configuration file (only lines 0 to 270 are relevant [up until "Query logging"]), the rest is the default configuration):

**[https://ptpb.pw/wm1L](url)**

Some additional information:

- I am using Arch Linux with the Linux LTS kernel, version 4-14-49-1
- Downgrading `dnscrypt-proxy` to 2.0.14-2 restores functionality on reboot
- I am not running any intermediary services that use DNS like `dnsmasq`
- I use `NetworkManager` for handling connections
- I have IPv6 completely disabled in my kernel parameters

**Comment by jedisct1** [comment] 2018-06-14 23:15
Duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/480

**Closed as completed by jedisct1** 2018-06-14 23:15 UTC
Labels: systemd, linux
