### ISSUE TITLE
dnscrypt-proxy 2.0.40 - illegal instruction on arm

### ISSUE THREAD

**Issue by rugabunda** [DNSCrypt/dnscrypt-proxy#1242] opened 2020-03-22 10:39 UTC
After installing 2.0.40, dnscrypt repeatedly fails to launch, reverting to 2.0.39, just copying over the older executable fixed the issue. 

Using: dnscrypt-proxy-linux_arm-2.0.40.tar.gz

**Comment by jedisct1** [comment] 2020-03-22 11:23
Duplicate of https://github.com/DNSCrypt/dnscrypt-proxy/issues/1240

Try the binary posted here. It would be useful to report if it works.

If not, try to download the file again from the download section.

The file in the download section has been compiled for ARMv5 (which it pretty old, and something we supposedly never supported), and the one in the comments above should be compatible with ARMv6.

**Closed as completed by jedisct1** 2020-03-22 11:23 UTC

**Comment by rugabunda** [comment] 2020-03-23 02:57
> Duplicate of #1240
> 
> Try the binary posted here. It would be useful to report if it works.
> 
> If not, try to download the file again from the download section.
> 
> The file in the download section has been compiled for ARMv5 (which it pretty old, and something we supposedly never supported), and the one in the comments above should be compatible with ARMv6.

works
