### ISSUE TITLE
Problem with cloudflare?

### ISSUE THREAD

**Issue by it-can** [DNSCrypt/dnscrypt-proxy#1141] opened 2020-01-08 08:13 UTC
Seeing this error in my syslog on my raspberry pi...

```
Jan  8 09:11:48 raspberrypi dnscrypt-proxy[6473]: [2020-01-08 09:11:48] [ERROR] Certificate hash [eb7525f88f0d9458f81a995019bfd34cb89ccdc957e7b0ef315f10f897638118] not found for [cloudflare]
```

**Comment by welwood08** [comment] 2020-01-08 08:19
Duplicate of #1140.

**Closed as completed by welwood08** 2020-01-08 08:19 UTC
