### ISSUE TITLE
How to exclude sources in Public Resolver list or any list

### ISSUE THREAD

**Issue by qjn1** [DNSCrypt/dnscrypt-proxy#778] opened 2019-04-06 04:50 UTC
I read the documentation on configuring static and sources, but nothing mentions how to exclude certain sources from being used, apart from filters but it doesn't help much in my case.

**Comment by Mikaela** [comment] 2019-04-06 07:25
I think this is a duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/735 and you use e.g. `disabled_server_names = ['cloudflare-ipv6', 'cloudflare']`  which seems to have been introduced in 2.0.20 (Debian Testing&Unstable are on 2.0.19).

**Comment by jedisct1** [comment] 2019-04-06 14:10
If you are actually talking about sources, in order to disable one, just delete or comment it.

**Closed as completed** 2019-04-07 10:05 UTC

**Comment by qjn1** [comment] 2019-04-09 17:11
> I think this is a duplicate of #735 and you use e.g. `disabled_server_names = ['cloudflare-ipv6', 'cloudflare']` which seems to have been introduced in 2.0.20 (Debian Testing&Unstable are on 2.0.19).

I believe this only works if you're using the 'static' setting. I'm using the public source list.

> If you are actually talking about sources, in order to disable one, just delete or comment it.

I'm using the public-resolvers and like to remove Cloudflare, I commented out Cloudflare yet it throws out this error: `[2019-04-09 13:02:29] [CRITICAL] Unable to use source [public-resolvers]: [Invalid signature]
[2019-04-09 13:02:29] [FATAL] No servers configured` after a restart. I'm aware it states there are no configured servers to use, though not sure how that's possible as there are plenty of servers uncommented and available for use.

**Comment by jedisct1** [comment] 2019-04-09 17:19
Use `disabled_server_names = ['cloudflare-ipv6', 'cloudflare']`.
