### ISSUE TITLE
Error: "domain" does not look like a port.

### ISSUE THREAD

**Issue by bphd** [DNSCrypt/dnscrypt-proxy#1500] opened 2020-10-28 12:32 UTC
https://github.com/dnscrypt/dnscrypt-proxy/wiki/Installation-linux

```
Type the following command:

ss -lp 'sport = :domain'

This may ouptut something similar to:

tcp    LISTEN     0      128    127.0.0.1:domain                *:*                     users:(("unbound",pid=28146,fd=6))
tcp    LISTEN     0      128    127.0.0.1:domain                *:*                     users:(("unbound",pid=28146,fd=4))
```

```bash
$ ss -lp 'sport = :domain'
Error: "domain" does not look like a port.
```

**Comment by jedisct1** [comment] 2020-10-28 12:40
Try to replace it with `53` maybe?

**Comment by bphd** [comment] 2020-10-28 12:52
> Try to replace it with `53` maybe?

Try to say it in the manual maybe?

It's not even defined as a variable as intended by `bash`, you're doing it all wrong

**Comment by ianbashford** [comment] 2020-10-28 15:42
@bphd  I don't think any slight was intended; it was just a friendly suggestion.

If :domain isn't resolving, it's likely the configuration of /etc/nsswitch.conf  or a lack of /etc/services accessible on your machine. 
The shell isn't the key here -- ss tries to resolve :domain (normally) by checking /etc/services (assuming nsswitch.conf refers to 'files').

On arch linux  nsswitch.conf contains this
```services: files``` 
then 
```
grep domain /etc/services
domain             53/tcp
domain             53/udp
...
```

Other flavours of linux may vary of course...

**Comment by ianbashford** [comment] 2020-10-31 12:02
@bphd I close this and assume you've been able to get by using port numbers explicitly or got help with the setup of ss on a linux forum somewhere.

**Closed as completed by ianbashford** 2020-10-31 12:02 UTC
