### ISSUE TITLE
Crash after ethernet link loss/restart

### ISSUE THREAD

**Issue by atomontage** [DNSCrypt/dnscrypt-proxy#238] opened 2018-03-17 17:28 UTC
```
 fatal error: sync: unlock of unlocked mutex
 goroutine 123055 [running]:
 runtime.throw(0x3cb231, 0x1e)
         /usr/lib/go/src/runtime/panic.go:619 +0x60 fp=0x12544dec sp=0x12544de0 pc=0x3cb7c
 sync.throw(0x3cb231, 0x1e)
         /usr/lib/go/src/runtime/panic.go:608 +0x24 fp=0x12544df8 sp=0x12544dec pc=0x3cb0c
 sync.(*Mutex).Unlock(0x1495f000)
         /usr/lib/go/src/sync/mutex.go:184 +0xdc fp=0x12544e10 sp=0x12544df8 pc=0x6cd84
 sync.(*RWMutex).Unlock(0x1495f000)
         /usr/lib/go/src/sync/rwmutex.go:132 +0x80 fp=0x12544e28 sp=0x12544e10 pc=0x6db0c
 main.(*ServerInfo).noticeBegin(0x1495f000, 0x125ce1a0)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/serversInfo.go:347 +0x5c fp=0x12544e54 sp=0x12544e28 pc=0x31b620
 main.(*Proxy).processIncomingQuery(0x125ce1a0, 0x1495f000, 0x3c01a2, 0x3, 0x3c01a2, 0x3, 0x13816000, 0x2b, 0xfff, 0x13d841d0, ...)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:275 +0x828 fp=0x12544f98 sp=0x12544e54 pc=0x3184f4
 main.(*Proxy).udpListener.func1(0x125ce1a0, 0x13816000, 0x2b, 0xfff, 0x13d841d0, 0x13218018)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:141 +0xbc fp=0x12544fd4 sp=0x12544f98 pc=0x322108
 runtime.goexit()
         /usr/lib/go/src/runtime/asm_arm.s:1015 +0x4 fp=0x12544fd4 sp=0x12544fd4 pc=0x67500
 created by main.(*Proxy).udpListener
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:135 +0x74
 goroutine 1 [chan receive, 19416 minutes]:
 github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service.(*systemd).Run.func1()
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service/service_systemd_linux.go:138 +0x94
 github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service.(*systemd).Run(0x125e3170, 0x11, 0x12639e20)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service/service_systemd_linux.go:139 +0xa4
 main.main()
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:67 +0x4e8
 goroutine 5 [syscall, 19416 minutes]:
 os/signal.signal_recv(0x0)
         /usr/lib/go/src/runtime/sigqueue.go:139 +0x130
 os/signal.loop()
         /usr/lib/go/src/os/signal/signal_unix.go:22 +0x14
 created by os/signal.init.0
         /usr/lib/go/src/os/signal/signal_unix.go:28 +0x30
 goroutine 11 [chan receive, 19416 minutes]:
 main.(*App).AppMain(0x125b2700, 0x125ce1a0)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:97 +0x34
 main.(*App).Start.func1(0x125b2700, 0x125ce1a0)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:87 +0x24
 created by main.(*App).Start
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:86 +0x104
 goroutine 12 [select, 19416 minutes, locked to thread]:
 runtime.gopark(0x3db6dc, 0x0, 0x3c0b33, 0x6, 0x18, 0x1)
         /usr/lib/go/src/runtime/proc.go:291 +0xfc
 runtime.selectgo(0x129757a0, 0x133b9ac0)
         /usr/lib/go/src/runtime/select.go:392 +0xea0
 runtime.ensureSigM.func1()
         /usr/lib/go/src/runtime/signal_unix.go:549 +0x1c0
 runtime.goexit()
         /usr/lib/go/src/runtime/asm_arm.s:1015 +0x4
 goroutine 34 [IO wait]:
 internal/poll.runtime_pollWait(0xb5bc3fc0, 0x72, 0x0)
         /usr/lib/go/src/runtime/netpoll.go:173 +0x44
 internal/poll.(*pollDesc).wait(0x134480b4, 0x72, 0x0, 0x0, 0x0)
         /usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x8c
 internal/poll.(*pollDesc).waitRead(0x134480b4, 0x144b2000, 0xfff, 0xfff)
         /usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x2c
 internal/poll.(*FD).ReadFrom(0x134480a0, 0x144b2000, 0xfff, 0xfff, 0x0, 0x0, 0x0, 0x0, 0x0)
         /usr/lib/go/src/internal/poll/fd_unix.go:207 +0x134
 net.(*netFD).readFrom(0x134480a0, 0x144b2000, 0xfff, 0xfff, 0x2218c, 0x13d84208, 0x8, 0x8, 0x37c348)
         /usr/lib/go/src/net/fd_unix.go:208 +0x38
 net.(*UDPConn).readFrom(0x13218018, 0x144b2000, 0xfff, 0xfff, 0x45858, 0x31723c, 0x12974f90, 0x12974fb0)
         /usr/lib/go/src/net/udpsock_posix.go:47 +0x38
 net.(*UDPConn).ReadFrom(0x13218018, 0x144b2000, 0xfff, 0xfff, 0xfff, 0xfff, 0x12ab60b0, 0x13218018, 0x0)
         /usr/lib/go/src/net/udpsock.go:118 +0x58
 main.(*Proxy).udpListener(0x125ce1a0, 0x13218018)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:130 +0xe4
 created by main.(*Proxy).udpListenerFromAddr
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:152 +0xb8
 goroutine 35 [IO wait, 113 minutes]:
 internal/poll.runtime_pollWait(0xb5bc3f40, 0x72, 0x0)
         /usr/lib/go/src/runtime/netpoll.go:173 +0x44
 internal/poll.(*pollDesc).wait(0x13448104, 0x72, 0xbcd00, 0x0, 0x0)
         /usr/lib/go/src/internal/poll/fd_poll_runtime.go:85 +0x8c
 internal/poll.(*pollDesc).waitRead(0x13448104, 0xffffff00, 0x0, 0x0)
         /usr/lib/go/src/internal/poll/fd_poll_runtime.go:90 +0x2c
 internal/poll.(*FD).Accept(0x134480f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
         /usr/lib/go/src/internal/poll/fd_unix.go:372 +0x174
 net.(*netFD).accept(0x134480f0, 0x13426468, 0x0, 0x45858)
         /usr/lib/go/src/net/fd_unix.go:238 +0x20
 net.(*TCPListener).accept(0x13218030, 0x129707d8, 0x64b08, 0x129707d4)
         /usr/lib/go/src/net/tcpsock_posix.go:136 +0x20
 net.(*TCPListener).Accept(0x13218030, 0x3db334, 0x4159f8, 0x13426468, 0x125ce1a0)
         /usr/lib/go/src/net/tcpsock.go:259 +0x3c
 main.(*Proxy).tcpListener(0x125ce1a0, 0x13218030)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:159 +0x40
 created by main.(*Proxy).tcpListenerFromAddr
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:187 +0xb8
 goroutine 40 [sleep]:
 time.Sleep(0xf8475800, 0xd)
         /usr/lib/go/src/runtime/time.go:102 +0x154
 main.(*Proxy).prefetcher.func1(0x125ce318, 0x125ce1a0)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:121 +0x214
 created by main.(*Proxy).prefetcher
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:107 +0x34
 goroutine 41 [sleep, 201 minutes]:
 time.Sleep(0xc2e28000, 0xd18)
         /usr/lib/go/src/runtime/time.go:102 +0x154
 main.(*Proxy).StartProxy.func1(0x125ce1a0)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:100 +0x20
 created by main.(*Proxy).StartProxy
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:94 +0x338
 goroutine 123003 [runnable]:
 sync.(*RWMutex).RLock(0x1264e5e0)
         /usr/lib/go/src/sync/rwmutex.go:43 +0x58
 main.(*PluginCloak).Eval(0x1264e5e0, 0x146a7040, 0x13236370, 0x0, 0x0)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/plugin_cloak.go:105 +0x120
 main.(*PluginsState).ApplyQueryPlugins(0x146a7040, 0x125ce2f8, 0x12d6e000, 0x2b, 0xfff, 0x21a3bbde, 0x6b18c6d9, 0x46ec380d, 0x20182d3d, 0xb449a5b3)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/plugins.go:127 +0x170
 main.(*Proxy).processIncomingQuery(0x125ce1a0, 0x1495f000, 0x3c01a2, 0x3, 0x3c01a2, 0x3, 0x12d6e000, 0x2b, 0xfff, 0x12ab60b0, ...)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:254 +0x110
 main.(*Proxy).udpListener.func1(0x125ce1a0, 0x12d6e000, 0x2b, 0xfff, 0x12ab60b0, 0x13218018)
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:141 +0xbc
 created by main.(*Proxy).udpListener
         /home/chris/aur/dnscrypt-proxy-go/src/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/proxy.go:135 +0x74
```

**Comment by jedisct1** [comment] 2018-03-17 21:38
Lines numbers don't match, so I guess this is an old version.

Probably a duplicate of  #201.

**Closed as completed by jedisct1** 2018-03-17 21:38 UTC
Labels: duplicate
