### ISSUE TITLE
add china dns

### ISSUE THREAD

**Issue by Potterli20** [DNSCrypt/dnscrypt-proxy#1303] opened 2020-04-30 16:00 UTC
## add china dns
My China's DNS:
https://dns-api.trli.xyz/dns-query
tls://dns-api.trli.xyz

My Foreign DNS:
https://dns2-api.trli.xyz:444/dns-query
tls://dns2-api.trli.xyz

Other China's DNS:
https://dns.alidns.com/dns-query
tls://dns.alidns.com
****

**Comment by jkle112** [comment] 2020-05-01 02:34
Thank you ,I add these in my system.

**Comment by jedisct1** [comment] 2020-05-01 07:08
Duplicate of https://github.com/DNSCrypt/dnscrypt-resolvers/issues/269

**Closed as completed** 2020-05-01 13:59 UTC
Labels: duplicate
