### ISSUE TITLE
Outgoing Network interfaces

### ISSUE THREAD

**Issue by dtouzeau** [DNSCrypt/dnscrypt-proxy#1437] opened 2020-08-04 15:17 UTC
## Is your feature request related to a problem?
When using a server with multiples Interfaces and same metrics, DNScypt-proxy chose the first available that is not the right interface for outgoing requests.

## Describe the solution you'd like
Adding a paremeter 

```
## List of local addresses and ports to send outgoing requests.
##  Can be IPv4 and/or IPv6.
## Example with both IPv4 and IPv6:
outgoing_addresses = ['127.0.0.1:53', '[::1]:53']
```

**Comment by welwood08** [comment] 2020-08-04 21:17
Looks like the second duplicate of #1362 in 24 hours. Thank you for the report but please do search for similar issues first.

**Comment by jedisct1** [comment] 2020-08-04 21:44
Maybe not a duplicate.

The way I understand this it that it's a feature request about having a way to choose the source IP address for connections to upstream servers.

**Comment by welwood08** [comment] 2020-08-04 22:08
My bad, having re-read it that makes sense. I guess it would need the same technique to implement at least.

**Comment by dtouzeau** [comment] 2020-08-04 22:31
> 
> 
> My bad, having re-read it that makes sense. I guess it would need the same technique to implement at least.

Yes you understand the feature request...

**Closed as completed** 2020-09-13 18:15 UTC
Labels: timeout
