### ISSUE TITLE
Bat files won't work

### ISSUE THREAD

**Issue by ghost** [DNSCrypt/dnscrypt-proxy#394] opened 2018-04-19 23:37 UTC
I use last 2.0.10 version on Win10 x64 LTSB and .bat files for install/restart/remove service is not working, command line just opens and closes many times, like in this issues:
https://github.com/jedisct1/dnscrypt-proxy/issues/386
https://github.com/jedisct1/dnscrypt-proxy/issues/340
https://github.com/jedisct1/dnscrypt-proxy/issues/336

You say it's been fixed, but it's not. I can only install service manually from powershell cmd.

**Comment by jedisct1** [comment] 2018-04-20 00:36
Duplicate of #369

Feel free to test whatever has been discussed here and to report what has to be done so that they work for you.

**Closed as completed by jedisct1** 2018-04-20 00:36 UTC
Labels: duplicate, windows
