### ISSUE TITLE
Requests received on a wildcard are answered based on the interface and not on the destination IP

### ISSUE THREAD

**Issue by FiloSottile** [DNSCrypt/dnscrypt-proxy#1433] opened 2020-08-03 21:11 UTC
## *Who* is the bug affecting?

This issue affects users of dnscrypt-proxy who

1. listen on the wildcard address
2. have multiple interfaces
3. have requests coming from one interface for the IP of a different interface

## *What* is affected by this bug?

dnscrypt-proxy answers come from the IP of the interface they are sent from, instead of the IP they were sent to.

Clients discard those answers.

## *Where* does it happen?

OpenWRT, but probably any Linux

```
root@turris:~# uname -a
Linux turris 4.14.180 #0 SMP Sat May 16 18:32:20 2020 armv7l GNU/Linux
root@turris:~# dnscrypt-proxy -version
2.0.44
```

## *How* do we replicate the issue?

Configure a Linux machine with two interfaces and two IPs, for example `lan` with IP `172.27.1.1` and `vpn` with IP `172.27.2.1`.

```
vpn       Link encap:UNSPEC  HWaddr 00-00-00-00-00-00-00-00-00-00-00-00-00-00-00-00
          inet addr:172.27.2.1  P-t-P:172.27.2.1  Mask:255.255.255.255
          UP POINTOPOINT RUNNING NOARP  MTU:1420  Metric:1

lan       Link encap:Ethernet  HWaddr D8:58:D7:00:41:95
          inet addr:172.27.1.1  Bcast:172.27.1.255  Mask:255.255.255.0
          inet6 addr: fe80::da58:d7ff:fe00:4195/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
```

Run dnscrypt-proxy listening on the wildcard address.

```
listen_addresses = ['0.0.0.0:53']
```

Make a request over one interface to the IP of the other one, for example to `172.27.1.1` over the `vpn` interface.

```
$ dig @172.27.1.1 example.com
;; reply from unexpected source: 172.27.2.1#53, expected 172.27.1.1#53
```

```
16:53:32.258715 IP 172.27.2.100.50701 > 172.27.1.1.53: 25155+ [1au] A? example.com. (40)
16:53:32.259174 IP 172.27.2.1.53 > 172.27.2.100.50701: 25155 1/0/1 A 93.184.216.34 (56)
```

## Expected behavior (i.e. solution)

dnscrypt-proxy should send the answer from the address that the request was sent to.

It should be fixable by using the `golang.org/x/net/ipv4` package to both obtain the destination IP and set the source IP.

## Other Comments

This is specifically an issue when listening on wildcard addresses, if dnscrypt-proxy is configured to listen on specific addresses it will work correctly, but that requires keeping the IPs in the dnscrypt-proxy configuration in sync with the system.

This is a common issue I have reported to various DNS servers over the years.

**Comment by welwood08** [comment] 2020-08-03 21:19
Sounds like a duplicate of #1362, which already notes the suggested workaround. I don't think anybody has looked at the code more closely yet, but thank you for providing reproduction steps. If you disagree about it being the same issue, please feel free to re-open.

**Closed as completed by welwood08** 2020-08-03 21:19 UTC
Labels: duplicate
