### ISSUE TITLE
service install fails (freebsd)

### ISSUE THREAD

**Issue by mike-pt** [DNSCrypt/dnscrypt-proxy#157] opened 2018-02-20 02:36 UTC
```
[2018-02-20 02:31:20] [NOTICE] Source [https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md] loaded
[2018-02-20 02:31:20] [NOTICE] dnscrypt-proxy 2.0.1
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x6451df]

goroutine 1 [running]:
github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service.Control(0x0, 0x0, 0x7fffffffee20, 0x7, 0x1, 0x7c0aa0)
        /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/vendor/github.com/kardianos/service/service.go:341 +0x31f
main.main()
        /home/travis/gopath/src/github.com/jedisct1/dnscrypt-proxy/dnscrypt-proxy/main.go:47 +0x414
```

Any idea why this happens on FreeBSD?

**Comment by jedisct1** [comment] 2018-02-20 03:57
Duplicate of https://github.com/jedisct1/dnscrypt-proxy/issues/154

**Closed as completed by jedisct1** 2018-02-20 03:57 UTC
Labels: duplicate

**Comment by mike-pt** [comment] 2018-02-20 05:25
Ah sorry I searched for the error but I see now why It didn't find it.. Sorry for the double noise.
