### ISSUE TITLE
Crash under MIPS64 - fatal error: netpoll failed 

### ISSUE THREAD

**Issue by acejacek** [DNSCrypt/dnscrypt-proxy#1513] opened 2020-11-17 21:52 UTC
dnscrypt-proxy version 2.0.44, running on EdgeRouter ERLite-3.
I cannot reproduce the error, after it occures, dnscrypt-proxy process crashes.

In logs there are references to x64 source, but the router is running MIPS64.

Log `dnscrypt-proxy.err`:

```log
runtime: epollwait on fd 4 failed with 22
fatal error: runtime: netpoll failed

runtime stack:
runtime.throw(0x5efd55, 0x17)
	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/panic.go:1116 +0x6c
runtime.netpoll(0x0, 0xc00002a800)
	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/netpoll_epoll.go:123 +0x498
runtime.sysmon()
	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/proc.go:4521 +0x440
runtime.mstart1()
	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/proc.go:1097 +0xf4
runtime.mstart()
	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/proc.go:1062 +0x68

goroutine 1 [chan receive]:
github.com/kardianos/service.(*sysv).Run.func1()
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/vendor/github.com/kardianos/service/service_sysv_linux.go:147 +0xd8
github.com/kardianos/service.(*sysv).Run(0xc00001d710, 0x5eaa2a, 0xf)
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/vendor/github.com/kardianos/service/service_sysv_linux.go:148 +0xf4
main.main()
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/dnscrypt-proxy/main.go:107 +0xf14

goroutine 6 [runnable, locked to thread]:
syscall.SlicePtrFromStrings(0xc000144460, 0x7, 0x7, 0xc00010d2f0, 0x5, 0x5, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.4/x64/src/syscall/exec_unix.go:90 +0x238
syscall.Exec(0xffffab4ef4, 0x25, 0xc000122420, 0x4, 0x6, 0xc000144460, 0x7, 0x7, 0x0, 0x0)
	/opt/hostedtoolcache/go/1.14.4/x64/src/syscall/exec_unix.go:271 +0xd0
golang.org/x/sys/unix.Exec(...)
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/vendor/golang.org/x/sys/unix/syscall_unix.go:410
main.(*Proxy).dropPrivilege(0xc000098900, 0xc0001346dd, 0x6, 0xc000163880, 0x2, 0x2)
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/dnscrypt-proxy/privilege_linux.go:88 +0x81c
main.ConfigLoad(0xc000098900, 0xc000084500, 0x0, 0x0)
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/dnscrypt-proxy/config.go:582 +0x1870
main.(*App).AppMain(0xc00001d6e0)
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/dnscrypt-proxy/main.go:127 +0x48
main.(*App).Start.func1(0xc00001d6e0)
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/dnscrypt-proxy/main.go:118 +0x3c
created by main.(*App).Start
	/home/runner/work/dnscrypt-proxy/dnscrypt-proxy/dnscrypt-proxy/main.go:117 +0x60

goroutine 7 [syscall]:
os/signal.signal_recv(0x0)
	/opt/hostedtoolcache/go/1.14.4/x64/src/runtime/sigqueue.go:147 +0x150
os/signal.loop()
	/opt/hostedtoolcache/go/1.14.4/x64/src/os/signal/signal_unix.go:23 +0x34
created by os/signal.Notify.func1
	/opt/hostedtoolcache/go/1.14.4/x64/src/os/signal/signal.go:127 +0x60
```

**Comment by jedisct1** [comment] 2020-11-17 22:29
Duplicate of #1181

Remove `user_name` in your configuration file.

If you can recompile it, you can also try the current development code that includes some changes to the way this is handled.

**Closed as completed by jedisct1** 2020-11-17 22:29 UTC
